# Generated by .github/scripts/gen-homebrew-formula.sh — do not edit by hand.
class Marrow < Formula
  desc "Surface the parts of a GitHub PR that matter — an AI PR review TUI"
  homepage "https://github.com/Besendorfer/marrow"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.1/marrow-aarch64-apple-darwin.tar.gz"
      sha256 "f6a29c67018017d0ebb5cde3e492e84ffe124af327e002bdca095982680ad138"
    else
      url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.1/marrow-x86_64-apple-darwin.tar.gz"
      sha256 "20ca037e82529ebf58649e9aceb7f8cf7f14678ec2b01dcbade8808d00166068"
    end
  end

  on_linux do
    url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.1/marrow-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "6a9b1cbba75e48f1bd1d897000f95cd901ce8835f7f3266326f1d7c876bbd900"
  end

  def install
    bin.install "marrow"
  end

  test do
    assert_match "marrow", shell_output("#{bin}/marrow --help 2>&1")
  end
end
