# Generated by .github/scripts/gen-homebrew-formula.sh — do not edit by hand.
class Marrow < Formula
  desc "Surface the parts of a GitHub PR that matter — an AI PR review TUI"
  homepage "https://github.com/Besendorfer/marrow"
  version "0.1.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.2/marrow-aarch64-apple-darwin.tar.gz"
      sha256 "08e7507929bc284e7c7612af7e98bc1ac57f553cb7a13bac84c87284db8abe01"
    else
      url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.2/marrow-x86_64-apple-darwin.tar.gz"
      sha256 "3936e622f9217483c9eb7b83c021144cf67312b172c101ebfd346e71dac63cd6"
    end
  end

  on_linux do
    url "https://github.com/Besendorfer/marrow/releases/download/cli-v0.1.0-alpha.2/marrow-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "cb8582ba5593cce4a753b97fd0ae4cbf4fe557c43aae3e899dab68668fc9f9ff"
  end

  def install
    bin.install "marrow"
  end

  test do
    assert_match "marrow", shell_output("#{bin}/marrow --help 2>&1")
  end
end
